server:
  port: 8001
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: consul-order
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.impl.Store
  mapper-locations: classpath:mappers/*.xml

eureka:
  instance:
    instance-id: ${spring.application.name}:8001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka

